### ISSUE TITLE
Difference with Save-Data request header

### ISSUE THREAD

**Issue by niutech** [boramalper/light-web-pages#1]
What's the difference between your `LWP: 1` header and the already existing one [`Save-Data: on`](https://developers.google.com/web/updates/2016/02/save-data)? No need to reinvent the wheel.

**Comment by boramalper** [comment]
Sorry for such a belated reply, and thanks for letting me know! I haven't heard about it until now, checked MDN for further info but it wasn't documented. I've [filed an issue](https://github.com/mdn/sprints/issues/1379) in their bug tracker just now, and will edit my README too.
